# Generated by Django 2.2.13 on 2021-01-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='toggle_choice',
            field=models.IntegerField(choices=[(0, 'Practice'), (1, 'Teach')], default=0),
        ),
    ]
